version: '3'

networks:
  cvbp_craft:

services:
  nginx:
    image: nginx:latest
    container_name: cvbp_nginx
    ports:
      - "8088:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/cvbp.jeziordev.crt:/etc/nginx/cvbp.jeziordev.crt
      - ./docker/nginx/cvbp.jeziordev.key:/etc/nginx/cvbp.jeziordev.key
    depends_on:
      - php
      - mysql
      - redis
      - mailhog
    networks:
      - cvbp_craft

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cvbp_php
    working_dir: /var/www/html
    volumes:
      - ./docker/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./:/var/www/html
    environment:
      - REDIS_HOST=cvbp_redis
    ports:
      - "9000:9000"
    networks:
      - cvbp_craft

  mysql:
    image: mysql:5.7.22
    container_name: cvbp_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: cvbp_db
      MYSQL_USER: cvbp_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - cvbp_craft

  redis:
    image: redis:4.0
    container_name: cvbp_redis
    ports:
      - "6382:6379"
    networks:
      - cvbp_craft

  mailhog:
    image: mailhog/mailhog
    container_name: cvbp_mailhog
    ports:
      - 2025:1025
      - 9025:8025
    networks:
      - cvbp_craft
